<center><img src='https://raw.githubusercontent.com/Jangrae/img/master/title.png' width=500/></center>

# 학습 목표

- 리스트와 딕셔너리에서 데이터프레임을 만들 수 있습니다.
- 파일에서 읽어와 데이터프레임을 만들 수 있습니다.
- 임의의 값을 갖는 데이터프레임을 만들 수 있습니다.
- 데이터프레임의 인덱스를 변경하거나 초기화 할 수 있습니다.

https://github.com/Jangrae/ipynb/blob/main/02_%EB%8D%B0%EC%9D%B4%ED%84%B0%ED%94%84%EB%A0%88%EC%9E%84_%EB%A7%8C%EB%93%A4%EA%B8%B0.ipynb

# 2. 데이터프레임 만들기

## 2.1. 데이터프레임 이해

### 2.1.1. 데이터프레임이란


- Pandas 사용 목적이 데이터프레임을 사용하기 위한 목적으로 봐도 됩니다.
- 데이터를 처리, 조회, 분석하는 가장 효율적인 방법이 데이터프레임을 사용하는 것입니다.
- 데이터프레임은 시리즈와는 달리 **하나 이상의 열**을 갖는 형태입니다.
- 일반적으로 접하게 되는 **테이블** 형태, **엑셀** 형태로 생각하시면 됩니다.
- 직접 만들 수 있으나 보통은 **csv 파일**, **엑셀 파일** 또는 DB에서 읽어옵니다.

<img src='https://raw.githubusercontent.com/Jangrae/img/master/dataframe_sample.png' width=800 align="left"/>

### 2.1.2. 데이터프레임 형태

- 데이터프레임은 **인덱스(=행 이름)**와 **열 이름**이 있고 없고에 따라 다른 형태를 갖습니다.
- 인덱스란 행을 지정할 때 사용하는 정보이고, 열 이름은 열을 지정할 때 사용하는 정보입니다.

<img src='https://raw.githubusercontent.com/Jangrae/img/master/dataframe05.png' width=450 align="left"/>

**1) 인덱스와 열 이름이 없는 형태**

- 우선 인덱스와 열 이름이 없는 데이터프레임 형태입니다.
- 열 이름이 없는 데이터프레임은 실무에서는 자주 볼 수 없을 것입니다.

<img src='https://raw.githubusercontent.com/Jangrae/img/master/dataframe01.png' width=380 align="left"/>

**2) 열 이름을 지정한 형태**

- 열 이름만 지정한 데이터프레임 형태입니다.
- 특별히 인덱스를 지정할 필요가 없는 경우가 많으므로 자주 보게 되는 형태입니다.

<img src='https://raw.githubusercontent.com/Jangrae/img/master/dataframe02.png' width=380 align="left"/>

**3) 인덱스와 열 이름을 지정한 형태**

- 인덱스와 열 이름 모두를 지정한 데이터프레임 형태입니다.
- 대부분 주식 시세와 같은 날짜가 인덱스로 지정되는 경우입니다.

<img src='https://raw.githubusercontent.com/Jangrae/img/master/dataframe03.png' width=350 align="left"/>

**4) 문자열 데이터를 갖는 데이터프레임**

- 대부분 분석 대상은 숫자일 것입니다.
- 하지만 다음과 같이 문자열을 갖는 데이터프레임도 자주 접하게 됩니다.

<img src='https://raw.githubusercontent.com/Jangrae/img/master/dataframe04.png' width=700 align="left"/>

## 2.2. 데이터프레임 직접 만들기

- **pd.DataFrame()** 함수를 사용해 데이터프레임을 만듭니다.
- 대부분 리스트, 딕셔너리, Numpy 배열로부터 데이터프레임을 만듭니다.
- 데이터프레임은 여러 열을 가지므로 **인덱스** 외에도 **열 이름**에 대한 **설정**이 필요합니다.
- 데이터프레임을 만들 때 **열 이름**을 직접 지정하거나, 나중에 변경할 수 있습니다.
- 열 이름을 지정하지 않으면 **열 번호**에 기반한 정수(0, 1, 2...)가 열 이름이 됩니다.
- 우선 다음과 같이 관련 라이브러리를 불러옵니다.

In [12]:
# 라이브러리 불러오기
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

### 2.2.1. 리스트로  만들기

- 인덱스를 지정하지 않으면 행 번호가 인덱스, 열 번호가 열 이름이 됩니다.

In [13]:
# 리스트 만들기
stock = [[94500, 92100, 92200, 92300],
         [96500, 93200, 95900, 94300],
         [93400, 91900, 93400, 92100],
         [94200, 92100, 94100, 92400],
         [94500, 92500, 94300, 92600]]

# 데이터프레임 만들기
df = pd.DataFrame(stock)

# 확인
df.head()

0      1      2      3
0  94500  92100  92200  92300
1  96500  93200  95900  94300
2  93400  91900  93400  92100
3  94200  92100  94100  92400
4  94500  92500  94300  92600

- 필요하면 인덱스와 열 이름을 별도로 지정할 수 있습니다.

In [14]:
# 리스트 만들기
stock = [[94500, 92100, 92200, 92300],
         [96500, 93200, 95900, 94300],
         [93400, 91900, 93400, 92100],
         [94200, 92100, 94100, 92400],
         [94500, 92500, 94300, 92600]]
dates = ['2019-02-15', '2019-02-16', '2019-02-17', '2019-02-18', '2019-02-19']
names = ['High', 'Low', 'Open', 'Close']

# 데이터프레임 만들기
df = pd.DataFrame(stock, index=dates, columns=names)

# 확인
df.head()

High    Low   Open  Close
2019-02-15  94500  92100  92200  92300
2019-02-16  96500  93200  95900  94300
2019-02-17  93400  91900  93400  92100
2019-02-18  94200  92100  94100  92400
2019-02-19  94500  92500  94300  92600

### 2.2.2. 딕셔너리로 만들기

- 딕셔너리로 데이터프레임을 만들면 딕셔너리의 **키**가 **열 이름**이 됩니다.
- 인덱스를 지정하지 않으면 행 번호가 인덱스가 됩니다.

In [15]:
# 딕셔너리 만들기
dict = {'이름': ['홍길동', '한사랑', '일지매', '박여인'],
        '등급': ['Gold', 'Bronze', 'Silver', 'Gold'],
        '점수': [56000, 23000, 44000, 52000]}

# 확인
dict

{'등급': ['Gold', 'Bronze', 'Silver', 'Gold'],
 '이름': ['홍길동', '한사랑', '일지매', '박여인'],
 '점수': [56000, 23000, 44000, 52000]}

In [16]:
# 데이터프레임 만들기
df = pd.DataFrame(dict)

# 확인
df.head()

이름      등급     점수
0  홍길동    Gold  56000
1  한사랑  Bronze  23000
2  일지매  Silver  44000
3  박여인    Gold  52000

- 필요하면 인덱스를 별도로 지정할 수 있습니다.

In [17]:
# 딕셔너리 만들기
dict = {
   '이름': ['홍길동', '한사랑', '일지매', '박여인'],
   '등급': ['Gold', 'Bronze', 'Silver', 'Gold'],
   '점수': [56000, 23000, 44000, 52000]
}

# 데이터프레임 만들기(인덱스 지정함)
df = pd.DataFrame(dict, index=['C0001', 'C0002', 'C0003', 'C0004'])

# 확인
df.head()

이름      등급     점수
C0001  홍길동    Gold  56000
C0002  한사랑  Bronze  23000
C0003  일지매  Silver  44000
C0004  박여인    Gold  52000

### 2.2.3. 배열로  만들기

- 리스트 대신 배열을 사용해서 데이터프레임을 만들 수 있습니다.

In [18]:
# 배열 만들기
stock = np.array([[94500, 92100, 92200, 92300],
                  [96500, 93200, 95900, 94300],
                  [93400, 91900, 93400, 92100],
                  [94200, 92100, 94100, 92400],
                  [94500, 92500, 94300, 92600]])
dates = np.array(['2019-02-15', '2019-02-16', '2019-02-17', '2019-02-18', '2019-02-19'])
names = np.array(['High', 'Low', 'Open', 'Close'])

# 확인
print(stock)
print(dates)
print(names)

[[94500 92100 92200 92300]
 [96500 93200 95900 94300]
 [93400 91900 93400 92100]
 [94200 92100 94100 92400]
 [94500 92500 94300 92600]]
['2019-02-15' '2019-02-16' '2019-02-17' '2019-02-18' '2019-02-19']
['High' 'Low' 'Open' 'Close']


In [19]:
# 데이터프레임 만들기
df = pd.DataFrame(stock, index=dates, columns=names)

# 확인
df.head()

High    Low   Open  Close
2019-02-15  94500  92100  92200  92300
2019-02-16  96500  93200  95900  94300
2019-02-17  93400  91900  93400  92100
2019-02-18  94200  92100  94100  92400
2019-02-19  94500  92500  94300  92600

<img src='https://raw.githubusercontent.com/jangrae/img/master/practice_01.png' width=120 align="left"/>

[문1] 아래 주어진 리스트들을 사용해 score 데이터프레임을 만들고 확인해 보세요.

In [20]:
# 리스트 만들기
list_score = [[80, 75, 100, 90, 80],
              [85, 70,  80, 95, 90],
              [75, 80,  85, 90, 90],
              [85, 65,  85, 75, 70],
              [70, 85,  90, 85, 95]]
              
# 인덱스: ['홍길동', '한사랑', '일지매', '박여인', '강우동']
list_index = ['홍길동', '한사랑', '일지매', '박여인', '강우동']

# 열이름: ['국어', '영어', '수학', '과학', '역사']
list_col = ['국어', '영어', '수학', '과학', '역사']

# 데이터프레임 만들기
score = pd.DataFrame(list_score, index=list_index, columns=list_col)

# 확인
score

국어  영어   수학  과학  역사
홍길동  80  75  100  90  80
한사랑  85  70   80  95  90
일지매  75  80   85  90  90
박여인  85  65   85  75  70
강우동  70  85   90  85  95

## 2.3. CSV파일 읽어오기

- 분석용 데이터는 대부분 파일에서 읽어 가져옵니다.
- **read_csv()** 함수를 사용해서 CSV 파일에서 데이터를 읽어옵니다.

<img src='https://raw.githubusercontent.com/jangrae/img/master/titanic_simple.png' width=650 align="left"/>

**[주요옵션]**
- sep: 구분자 지정(기본값 = 콤마)
- header: 헤더가 될 행 번호 지정(기본값 = 0)
- index_col: 인덱스 열 지정(기본값 = False)
- names: 열 이름으로 사용할 문자열 리스트
- skiprows: 처음 몇 줄을 무시할 것인지 지정, 리스트로 지정 가능

In [21]:
# Titanic 데이터 불러오기
file_path = 'https://raw.githubusercontent.com/Jangrae/csv/master/titanic_simple.csv'
titanic = pd.read_csv(file_path, sep = ',', header=0, index_col=False)  

# 상위 20행만 확인
titanic.head(20)

PassengerId  Survived  Pclass  ...   Age     Fare      Embarked
0             1         0       3  ...  22.0   7.2500  Southhampton
1             2         1       1  ...  38.0  71.2833     Cherbourg
2             3         1       3  ...  26.0   7.9250  Southhampton
3             4         1       1  ...  35.0  53.1000  Southhampton
4             5         0       3  ...  35.0   8.0500  Southhampton
5             6         0       3  ...   NaN   8.4583    Queenstown
6             7         0       1  ...  54.0  51.8625  Southhampton
7             8         0       3  ...   2.0  21.0750  Southhampton
8             9         1       3  ...  27.0  11.1333  Southhampton
9            10         1       2  ...  14.0  30.0708     Cherbourg
10           11         1       3  ...   4.0  16.7000  Southhampton
11           12         1       1  ...  58.0  26.5500  Southhampton
12           13         0       3  ...  20.0   8.0500  Southhampton
13           14         0       3  ...  39.0  31.2750  Southhampton
14           15         0       3  ...  14.0   7.8542  Southhampton
15           16         1       2  ...  55.0  16.0000  Southhampton
16           17         0       3  ...   2.0  29.1250    Queenstown
17           18         1       2  ...   NaN  13.0000  Southhampton
18           19         0       3  ...  31.0  18.0000  Southhampton
19           20         1       3  ...   NaN   7.2250     Cherbourg

[20 rows x 8 columns]

**[참고] 엑셀 시트 읽기 & 쓰기**

- 엑셀 시트는 **read_excel()** 함수를 사용해 읽어옵니다.
- 엑셀 시트는 여러 형태를 가지므로 사용해야 할 옵션이 많을 수 있습니다.

<img src='https://raw.githubusercontent.com/jangrae/img/master/excel.png' width=600 align="left"/>

In [22]:
# 엑셀 시트 읽어오기
sample = pd.read_excel('sample.xlsx',
                       header=4, 
                       skiprows=[5], 
                       index_col=False, 
                       usecols=[1, 2, 3, 4, 5, 6],
                       sheet_name='실적2')  

# 확인
sample.head(10)

이름    1월    2월    3월    4월    5월
0  홍길동  6700  6800  7800  7000  5800
1  일지매  5600  5500  6700  7100  6200
2  한사랑  5200  5900  6500  6700  6500
3  강우동  5600  4900  6100  6900  7000
4  박여인  6100  6100  5800  7000  6500
5  한국인  5600  6200  6000  7100  6900

In [23]:
# 엑셀 시트 쓰기
sample.to_excel('sample2.xlsx')  

In [24]:
# csv 파일 쓰기
sample.to_csv('sample2.csv', encoding='CP949')  

<img src='https://raw.githubusercontent.com/jangrae/img/master/practice_01.png' width=120 align="left"/>

[문1] 아래 주어진 경로의 파일에서 데이터를 읽어와 데이터프레임 graduate 만들어 보세요.

- 파일 경로: 'https://raw.githubusercontent.com/Jangrae/csv/master/Graduate_apply.csv'

In [25]:
# graduate 데이터 불러오기
file_path = 'https://raw.githubusercontent.com/Jangrae/csv/master/Graduate_apply.csv'
graduate = pd.read_csv(file_path, sep = ',', header=0, index_col=False)  
graduate.head(10)

# 확인
graduate.head()

admit  gre   gpa  rank
0      0  380  3.61     3
1      1  660  3.67     3
2      1  800  4.00     1
3      1  640  3.19     4
4      0  520  2.93     4

[문2] 아래 주어진 경로의 stock.csv 파일을 읽어와 stock 데이터프레임을 만들어 보세요.

- 파일 경로: 'https://raw.githubusercontent.com/Jangrae/csv/master/stock.csv'

In [26]:
# stock 데이터 불러오기
file_path = 'https://raw.githubusercontent.com/Jangrae/csv/master/stock.csv'
stock = pd.read_csv(file_path, sep = ',', header=0, index_col=False)  

# 확인
stock.head()

Date      High       Low      Open     Close     Volume  Adj Close
0  2000-01-03  4.017857  3.631696  3.745536  3.997768  133949200   3.470226
1  2000-01-04  3.950893  3.613839  3.866071  3.660714  128094400   3.177650
2  2000-01-05  3.948661  3.678571  3.705357  3.714286  194580400   3.224152
3  2000-01-06  3.821429  3.392857  3.790179  3.392857  191993200   2.945139
4  2000-01-07  3.607143  3.410714  3.446429  3.553571  115183600   3.084645

## 2.4. 임의의 값을 갖는 데이터프레임 만들기

- 테스트용 데이터프레임을 만들 때 많이 사용하니 익혀두는 것이 좋습니다.

**[참고] 난수 발생 방법**

- random.**rand()**: 0부터 1사이의 균일 분포 임의 실수
- random.**randn()**: 가우시안 표준 정규 분포 임의 실수
- random.**randint()**: 균일 분포의 임의 정수

**1) 임의의 실수값**

- 일정 기간의 날짜 데이터를 만들어 내는 **date_range()** 함수도 기억하기 바랍니다.

In [27]:
# 2020-02-01 부터 날짜 10개 확인
pd.date_range('20200201', periods=10)

DatetimeIndex(['2020-02-01', '2020-02-02', '2020-02-03', '2020-02-04',
               '2020-02-05', '2020-02-06', '2020-02-07', '2020-02-08',
               '2020-02-09', '2020-02-10'],
              dtype='datetime64[ns]', freq='D')

In [28]:
# 임의의 실수를 갖는 10 x 4 형태의 2차원 배열 확인
np.random.randn(10, 4)

array([[ 0.72613006, -0.13273139,  1.15796492, -1.16838517],
       [-0.07294004,  1.40832344, -0.31088701, -1.0494978 ],
       [-0.43688673, -0.10174121, -1.13685911, -0.85993589],
       [ 0.31273209,  1.54989092, -0.89876531, -0.03704103],
       [-0.06520496,  0.61777597, -1.01982272,  0.85505744],
       [-2.56518442, -0.37143632,  1.29843396,  2.20745571],
       [-0.72809938, -0.27632444, -1.44290125,  0.78208283],
       [-0.2478463 , -1.11735959,  0.32210608,  2.43537443],
       [ 0.59127828, -0.19096124,  0.52251566, -0.50560185],
       [ 0.69437415, -1.11820211,  0.92854198, -0.61693249]])

- 함수들 기능을 확인했으니 이제 데이터프레임을 만들어봅니다.

In [29]:
# 2020-02-01 부터 날짜 10개 만들기
dates = pd.date_range('20200201', periods=10)

# 임의의 실수를 갖는 10 x 4 형태의 2차원 배열 만들기
nums = np.random.randn(10, 4)

# 데이터프레임 만들기
df = pd.DataFrame(nums, index=dates, columns=list('ABCD'))

# 확인
df.head(10)

A         B         C         D
2020-02-01  1.183048 -0.563557 -2.175789 -1.396082
2020-02-02 -0.478661  0.833146 -1.698021  2.212498
2020-02-03  0.241515  0.279844 -0.748485 -1.585713
2020-02-04  1.798377  1.029512 -1.239581 -0.856829
2020-02-05  0.778209 -1.625412 -1.942607  2.417967
2020-02-06  0.678420  0.556092  1.186296 -0.080556
2020-02-07  0.822350  0.862262 -0.136615  1.381764
2020-02-08  0.540114  0.537508  0.202033 -1.935105
2020-02-09  0.507248 -1.086480 -0.766072  0.927989
2020-02-10 -0.545863  0.616399  0.516084 -0.772954

**2) 임의의 정수값**

- 임의 정수를 만들 때는 적절한 범위를 지정해야 합니다.

In [30]:
# 지정한 범위 내의 임의의 정수를 갖는 10 x 4 형태의 2차원 배열 확인
np.random.randint(100000, 200000, size=(10, 4))

array([[191468, 113341, 160820, 143998],
       [156227, 196210, 171710, 154111],
       [142423, 138596, 137221, 138115],
       [132001, 135958, 101005, 120399],
       [172440, 157055, 196103, 158210],
       [113962, 184344, 196447, 172589],
       [121105, 131497, 161240, 116939],
       [121957, 154576, 175520, 109876],
       [148592, 105335, 187537, 116015],
       [111403, 120222, 147082, 102670]])

- 이제 데이터프레임을 만들어봅니다.

In [31]:
# 2020-02-01 부터 10개이 날짜 만들기
dates = pd.date_range('20200201', periods=10)

# 지정한 범위 내의 임의의 정수를 갖는 10 x 4 형태의 2차원 배열 만들기
nums = np.random.randint(100000, 200000, size=(10, 4))

# 열 이름으로 사용할 리스트 만들기
cols = ['col1', 'col2', 'col3', 'col4']

# 데이터프레임 만들기
df = pd.DataFrame(nums, index=dates, columns=cols)

# 확인
df.head(10)

col1    col2    col3    col4
2020-02-01  108414  192593  149545  137792
2020-02-02  142515  195109  175055  128126
2020-02-03  145473  182570  168278  171637
2020-02-04  167409  199829  123591  141130
2020-02-05  123971  170122  171499  180151
2020-02-06  177599  146164  191585  152625
2020-02-07  113226  111297  103154  180966
2020-02-08  109926  171292  105659  167554
2020-02-09  181618  157929  187416  105384
2020-02-10  134707  182190  199901  101496

## 2.5. 인덱스 다시 설정

- 일반 열을 인덱스 열로 설정하거나, 위치 인덱스로 초기화 할 수 있습니다.

In [32]:
# stock 데이터 불러오기
file_path = 'https://raw.githubusercontent.com/jangrae/csv/master/stock.csv'
stock = pd.read_csv(file_path, sep = ',')  

# 확인
stock.head()

Date      High       Low      Open     Close     Volume  Adj Close
0  2000-01-03  4.017857  3.631696  3.745536  3.997768  133949200   3.470226
1  2000-01-04  3.950893  3.613839  3.866071  3.660714  128094400   3.177650
2  2000-01-05  3.948661  3.678571  3.705357  3.714286  194580400   3.224152
3  2000-01-06  3.821429  3.392857  3.790179  3.392857  191993200   2.945139
4  2000-01-07  3.607143  3.410714  3.446429  3.553571  115183600   3.084645

**1) 일반 열을 인덱스로 지정**

- 파일을 불러올 때 **index_col** 옵션을 사용해 인덱스가 될 열을 선택할 수 있습니다.
- 파일을 불러온 후에 **set_index()** 메소드를 사용해 인덱스가 될 열을 설정할 수 있습니다.

In [33]:
# 기존 열 중에서 인덱스가 될 열 선택
stock.set_index('Date', inplace=True)

# 확인
stock.head()

High       Low      Open     Close     Volume  Adj Close
Date                                                                    
2000-01-03  4.017857  3.631696  3.745536  3.997768  133949200   3.470226
2000-01-04  3.950893  3.613839  3.866071  3.660714  128094400   3.177650
2000-01-05  3.948661  3.678571  3.705357  3.714286  194580400   3.224152
2000-01-06  3.821429  3.392857  3.790179  3.392857  191993200   2.945139
2000-01-07  3.607143  3.410714  3.446429  3.553571  115183600   3.084645

**2) 인덱스 이름 삭제**

In [34]:
# 인덱스 이름 삭제
stock.index.name = None

# 확인
stock.head()

High       Low      Open     Close     Volume  Adj Close
2000-01-03  4.017857  3.631696  3.745536  3.997768  133949200   3.470226
2000-01-04  3.950893  3.613839  3.866071  3.660714  128094400   3.177650
2000-01-05  3.948661  3.678571  3.705357  3.714286  194580400   3.224152
2000-01-06  3.821429  3.392857  3.790179  3.392857  191993200   2.945139
2000-01-07  3.607143  3.410714  3.446429  3.553571  115183600   3.084645

**3) 인덱스 초기화**

- **reset_index()** 메소드를 사용해 행 번호에 기반한 정수 값으로 인덱스를 초기화 할 수 있습니다.
- **drop=True**를 설정하면 기존 인덱스 열을 일반 열로 가져오지 않고 버립니다.(기본값=False)

In [35]:
# 인덱스 초기화
stock.reset_index(drop=False, inplace=True)

# 확인
stock.head()

index      High       Low      Open     Close     Volume  Adj Close
0  2000-01-03  4.017857  3.631696  3.745536  3.997768  133949200   3.470226
1  2000-01-04  3.950893  3.613839  3.866071  3.660714  128094400   3.177650
2  2000-01-05  3.948661  3.678571  3.705357  3.714286  194580400   3.224152
3  2000-01-06  3.821429  3.392857  3.790179  3.392857  191993200   2.945139
4  2000-01-07  3.607143  3.410714  3.446429  3.553571  115183600   3.084645

- 열 이름 변경

In [36]:
# 열 이름 변경
stock.rename(columns={'index': 'Date'}, inplace=True)

# 확인
stock.head()

Date      High       Low      Open     Close     Volume  Adj Close
0  2000-01-03  4.017857  3.631696  3.745536  3.997768  133949200   3.470226
1  2000-01-04  3.950893  3.613839  3.866071  3.660714  128094400   3.177650
2  2000-01-05  3.948661  3.678571  3.705357  3.714286  194580400   3.224152
3  2000-01-06  3.821429  3.392857  3.790179  3.392857  191993200   2.945139
4  2000-01-07  3.607143  3.410714  3.446429  3.553571  115183600   3.084645

<img src='https://raw.githubusercontent.com/jangrae/img/master/practice_01.png' width=120 align="left"/>

[문1] 아래 주어진 데이터프레임을 확인하고, 이어지는 셀에 코드를 완성해 보세요.

In [37]:
# 데이터프레임 만들기
dates = pd.date_range('20200201', periods=10)
nums = np.random.randn(10, 4)
df = pd.DataFrame(nums, index=dates, columns=list('ABCD'))

# 확인
df.head()

A         B         C         D
2020-02-01 -0.459288  0.711255  0.610122 -0.025113
2020-02-02 -0.429017 -0.976351  0.563082  1.408121
2020-02-03  0.228615 -0.518914  1.607185 -0.469066
2020-02-04 -1.020798 -2.166505 -0.830273 -0.890702
2020-02-05 -0.423352  1.593891 -1.492042  1.717594

In [38]:
# 인덱스 초기화
df.reset_index(drop=False, inplace=True)

# 확인
df.head()

index         A         B         C         D
0 2020-02-01 -0.459288  0.711255  0.610122 -0.025113
1 2020-02-02 -0.429017 -0.976351  0.563082  1.408121
2 2020-02-03  0.228615 -0.518914  1.607185 -0.469066
3 2020-02-04 -1.020798 -2.166505 -0.830273 -0.890702
4 2020-02-05 -0.423352  1.593891 -1.492042  1.717594

In [39]:
# 날짜 열 이름을 Date로 변경
df.rename(columns={'index': 'Date'}, inplace=True)

# 확인
df.head()

Date         A         B         C         D
0 2020-02-01 -0.459288  0.711255  0.610122 -0.025113
1 2020-02-02 -0.429017 -0.976351  0.563082  1.408121
2 2020-02-03  0.228615 -0.518914  1.607185 -0.469066
3 2020-02-04 -1.020798 -2.166505 -0.830273 -0.890702
4 2020-02-05 -0.423352  1.593891 -1.492042  1.717594

In [40]:
# 인덱스를 날짜 데이터가 있는 열로 다시 변경
df.set_index('Date', inplace=True)

# 확인
df.head()

A         B         C         D
Date                                              
2020-02-01 -0.459288  0.711255  0.610122 -0.025113
2020-02-02 -0.429017 -0.976351  0.563082  1.408121
2020-02-03  0.228615 -0.518914  1.607185 -0.469066
2020-02-04 -1.020798 -2.166505 -0.830273 -0.890702
2020-02-05 -0.423352  1.593891 -1.492042  1.717594

In [41]:
# 인덱스 이름 삭제
df.index.name = None

# 확인
df.head()

A         B         C         D
2020-02-01 -0.459288  0.711255  0.610122 -0.025113
2020-02-02 -0.429017 -0.976351  0.563082  1.408121
2020-02-03  0.228615 -0.518914  1.607185 -0.469066
2020-02-04 -1.020798 -2.166505 -0.830273 -0.890702
2020-02-05 -0.423352  1.593891 -1.492042  1.717594

<center><img src='https://raw.githubusercontent.com/Jangrae/img/master/end.png' width=300/></center>